// Generated by CoffeeScript 2.5.1
console.log(1 + 3);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWRhbS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxBZGFtLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFBLEdBQUUsQ0FBZCIsInNvdXJjZXNDb250ZW50IjpbImNvbnNvbGUubG9nIDErMyJdfQ==
//# sourceURL=c:\github\balls\coffee\Adam.coffee